#!/usr/bin/env bash
# configures Nginx server so that /redirect_me is redirecting to another page
# The redirection must be a “301 Moved Permanently”

sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html

# using sed command to perfprm redirections

string_for_replacement="server_name _;\n\trewrite ^\/\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
sudo service nginx reload
sudo nginx -t
